#!/usr/bin/env node
/**
 * Script to initialize a new Next.js 14+ project with TypeScript and Tailwind CSS
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function createProjectStructure(projectName) {
  const basePath = path.join(process.cwd(), projectName);

  // Create base directory
  if (!fs.existsSync(basePath)) {
    fs.mkdirSync(basePath, { recursive: true });
  }

  // Create directory structure
  const directories = [
    'app',
    'app/components',
    'app/lib',
    'app/utils',
    'app/styles',
    'public',
    '__tests__'
  ];

  directories.forEach(dir => {
    const dirPath = path.join(basePath, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  });

  return basePath;
}

function createPackageJson(basePath, projectName) {
  const packageJson = {
    name: projectName,
    version: "0.1.0",
    private: true,
    scripts: {
      "dev": "next dev",
      "build": "next build",
      "start": "next start",
      "lint": "next lint",
      "test": "jest"
    },
    dependencies: {
      "next": "^14.0.0",
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "@types/node": "^20.10.0",
      "@types/react": "^18.2.38",
      "@types/react-dom": "^18.2.17",
      "typescript": "^5.3.0",
      "tailwindcss": "^3.3.0",
      "postcss": "^8.4.31",
      "autoprefixer": "^10.4.16",
      "clsx": "^2.0.0",
      "tailwind-merge": "^2.0.0",
      "@better-auth/react": "^0.0.0-beta.1",
      "better-auth": "^0.0.0-beta.1"
    },
    devDependencies: {
      "@types/jest": "^29.5.8",
      "jest": "^29.7.0",
      "@testing-library/react": "^14.1.2",
      "@testing-library/jest-dom": "^6.1.4",
      "jest-environment-jsdom": "^29.7.0"
    }
  };

  fs.writeFileSync(path.join(basePath, 'package.json'), JSON.stringify(packageJson, null, 2));
}

function createTsConfig(basePath) {
  const tsConfig = {
    compilerOptions: {
      target: "es5",
      lib: ["dom", "dom.iterable", "es6"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [
        {
          name: "next"
        }
      ],
      paths: {
        "@/*": ["./*"]
      }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  };

  fs.writeFileSync(path.join(basePath, 'tsconfig.json'), JSON.stringify(tsConfig, null, 2));
}

function createTailwindConfig(basePath) {
  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;

  fs.writeFileSync(path.join(basePath, 'tailwind.config.js'), tailwindConfig);
}

function createPostCssConfig(basePath) {
  const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

  fs.writeFileSync(path.join(basePath, 'postcss.config.js'), postcssConfig);
}

function createRootLayout(basePath) {
  const layoutContent = `import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`;

  fs.writeFileSync(path.join(basePath, 'app', 'layout.tsx'), layoutContent);
}

function createHomePage(basePath) {
  const homeContent = `import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function Home() {
  return (
    <main className="container mx-auto p-4">
      <Card className="max-w-2xl mx-auto">
        <CardHeader>
          <CardTitle>Welcome to Next.js</CardTitle>
          <CardDescription>Modern React framework with TypeScript and Tailwind CSS</CardDescription>
        </CardHeader>
        <CardContent>
          <p className="mb-4">Get started by editing app/page.tsx</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 bg-gray-100 rounded-md">
              <h3 className="font-semibold mb-2">Features</h3>
              <ul className="list-disc pl-5 space-y-1">
                <li>Next.js 14+ with App Router</li>
                <li>TypeScript support</li>
                <li>Tailwind CSS styling</li>
                <li>Authentication with Better Auth</li>
              </ul>
            </div>
            <div className="p-4 bg-blue-50 rounded-md">
              <h3 className="font-semibold mb-2">Quick Start</h3>
              <ol className="list-decimal pl-5 space-y-1">
                <li>Run \`npm install\`</li>
                <li>Run \`npm run dev\`</li>
                <li>Open http://localhost:3000</li>
              </ol>
            </div>
          </div>
        </CardContent>
      </Card>
    </main>
  );
}
`;

  fs.writeFileSync(path.join(basePath, 'app', 'page.tsx'), homeContent);
}

function createGlobalCSS(basePath) {
  const cssContent = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`;

  fs.writeFileSync(path.join(basePath, 'app', 'globals.css'), cssContent);
}

function createApiClient(basePath) {
  const apiContent = `// lib/api.ts
import { getTokens } from '@better-auth/client/plugins';

class ApiClient {
  private baseUrl: string;

  constructor() {
    this.baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8000/api/v1';
  }

  private async request<T>(endpoint: string, options: RequestInit = {}): Promise<T> {
    const url = \`\${this.baseUrl}\${endpoint}\`;

    const headers = {
      'Content-Type': 'application/json',
      ...options.headers,
    };

    // Add auth token if available
    try {
      const tokens = await getTokens();
      if (tokens?.accessToken) {
        headers['Authorization'] = \`Bearer \${tokens.accessToken}\`;
      }
    } catch (error) {
      console.warn('Could not get auth tokens:', error);
    }

    const response = await fetch(url, {
      ...options,
      headers,
    });

    if (!response.ok) {
      throw new Error(\`API request failed: \${response.statusText}\`);
    }

    return response.json() as Promise<T>;
  }

  async get<T>(endpoint: string): Promise<T> {
    return this.request<T>(endpoint, { method: 'GET' });
  }

  async post<T>(endpoint: string, data?: any): Promise<T> {
    return this.request<T>(endpoint, {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async put<T>(endpoint: string, data?: any): Promise<T> {
    return this.request<T>(endpoint, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
  }

  async delete<T>(endpoint: string): Promise<T> {
    return this.request<T>(endpoint, { method: 'DELETE' });
  }
}

export const apiClient = new ApiClient();
`;

  const libDir = path.join(basePath, 'app', 'lib');
  if (!fs.existsSync(libDir)) {
    fs.mkdirSync(libDir, { recursive: true });
  }

  fs.writeFileSync(path.join(libDir, 'api.ts'), apiContent);
}

function createBetterAuthConfig(basePath) {
  const authContent = `// lib/auth.ts
import { createAuth } from '@better-auth/react';

export const { signIn, signOut, useSession } = createAuth({
  baseURL: process.env.NEXT_PUBLIC_BETTER_AUTH_URL || 'http://localhost:4000',
  fetchOptions: {
    credentials: 'include',
  },
});
`;

  const libDir = path.join(basePath, 'app', 'lib');
  fs.writeFileSync(path.join(libDir, 'auth.ts'), authContent);
}

function createEnvExample(basePath) {
  const envContent = `# API Configuration
NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
NEXT_PUBLIC_BETTER_AUTH_URL=http://localhost:4000

# Better Auth Configuration
BETTER_AUTH_SECRET=your-secret-key-here
BETTER_AUTH_URL=http://localhost:4000

# Database (if using database adapter)
DATABASE_URL=postgresql://user:password@localhost:5432/mydb
`;

  fs.writeFileSync(path.join(basePath, '.env.example'), envContent);
}

function createReadme(basePath, projectName) {
  const readmeContent = `# ${projectName}

This is a [Next.js](https://nextjs.org/) project bootstrapped with [\`create-next-app\`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).

## Getting Started

First, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
# or
bun dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

You can start editing the page by modifying \`app/page.tsx\`. The page auto-updates as you edit the file.

This project uses [\`next/font\`](https://nextjs.org/docs/basic-features/font-optimization) to automatically optimize and load Inter, a custom Google Font.

## Learn More

To learn more about Next.js, take a look at the following resources:

- [Next.js Documentation](https://nextjs.org/docs) - learn about Next.js features and API.
- [Learn Next.js](https://nextjs.org/learn) - an interactive Next.js tutorial.

You can check out [\`the GitHub repository\`](https://github.com/vercel/next.js/) - your feedback and contributions are welcome!

## Deploy on Vercel

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new?utm_medium=default-template&filter=next.js&utm_source=create-next-app&utm_campaign=create-next-app-readme) from the creators of Next.js.

Check out our [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.
`;

  fs.writeFileSync(path.join(basePath, 'README.md'), readmeContent);
}

function createJestConfig(basePath) {
  const jestConfig = `// jest.config.js
const nextJest = require('next/jest')

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/__tests__/setup.ts'],
  testEnvironment: 'jest-environment-jsdom',
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/$1',
  },
}

// createJestConfig is exported by this file's setup
module.exports = createJestConfig(customJestConfig)
`;

  fs.writeFileSync(path.join(basePath, 'jest.config.js'), jestConfig);
}

function createJestSetup(basePath) {
  const setupContent = `// __tests__/setup.ts
import '@testing-library/jest-dom';
`;

  fs.writeFileSync(path.join(basePath, '__tests__', 'setup.ts'), setupContent);
}

function main() {
  const args = process.argv.slice(2);

  if (args.length !== 1) {
    console.error('Usage: node init_nextjs_project.js <project_name>');
    process.exit(1);
  }

  const projectName = args[0];
  console.log(\`Creating new Next.js project: \${projectName}\`);

  const basePath = createProjectStructure(projectName);

  createPackageJson(basePath, projectName);
  createTsConfig(basePath);
  createTailwindConfig(basePath);
  createPostCssConfig(basePath);
  createRootLayout(basePath);
  createHomePage(basePath);
  createGlobalCSS(basePath);
  createApiClient(basePath);
  createBetterAuthConfig(basePath);
  createEnvExample(basePath);
  createReadme(basePath, projectName);
  createJestConfig(basePath);
  createJestSetup(basePath);

  console.log(\`\n✅ Project \${projectName} created successfully!\n`);
  console.log('Next steps:');
  console.log(\`1. cd \${projectName}\`);
  console.log('2. npm install');
  console.log('3. cp .env.example .env.local');
  console.log('4. npm run dev');
}

if (require.main === module) {
  main();
}
`;
